on: [push, pull_request]

name: Clippy

jobs:
  check:
    name: Check
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - run: sudo apt-get install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
